# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'armlab_gui.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(2263, 1522)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.kinectFrame = QtGui.QFrame(self.centralwidget)
        self.kinectFrame.setGeometry(QtCore.QRect(510, 60, 1241, 741))
        self.kinectFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.kinectFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.kinectFrame.setObjectName(_fromUtf8("kinectFrame"))
        self.videoDisplay = QtGui.QLabel(self.kinectFrame)
        self.videoDisplay.setGeometry(QtCore.QRect(530, 260, 221, 201))
        self.videoDisplay.setObjectName(_fromUtf8("videoDisplay"))
        self.OutputFrame = QtGui.QFrame(self.centralwidget)
        self.OutputFrame.setGeometry(QtCore.QRect(40, 60, 421, 581))
        self.OutputFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.OutputFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.OutputFrame.setObjectName(_fromUtf8("OutputFrame"))
        self.JointCoordLabel = QtGui.QLabel(self.OutputFrame)
        self.JointCoordLabel.setGeometry(QtCore.QRect(10, 0, 281, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.JointCoordLabel.setFont(font)
        self.JointCoordLabel.setObjectName(_fromUtf8("JointCoordLabel"))
        self.WorldCoordLabel = QtGui.QLabel(self.OutputFrame)
        self.WorldCoordLabel.setGeometry(QtCore.QRect(10, 300, 311, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.WorldCoordLabel.setFont(font)
        self.WorldCoordLabel.setObjectName(_fromUtf8("WorldCoordLabel"))
        self.layoutWidget_2 = QtGui.QWidget(self.OutputFrame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(170, 40, 131, 234))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.rdoutBaseJC = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.rdoutBaseJC.setFont(font)
        self.rdoutBaseJC.setObjectName(_fromUtf8("rdoutBaseJC"))
        self.verticalLayout_8.addWidget(self.rdoutBaseJC, 0, QtCore.Qt.AlignLeft)
        self.rdoutShoulderJC = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.rdoutShoulderJC.setFont(font)
        self.rdoutShoulderJC.setObjectName(_fromUtf8("rdoutShoulderJC"))
        self.verticalLayout_8.addWidget(self.rdoutShoulderJC, 0, QtCore.Qt.AlignLeft)
        self.rdoutElbowJC = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.rdoutElbowJC.setFont(font)
        self.rdoutElbowJC.setObjectName(_fromUtf8("rdoutElbowJC"))
        self.verticalLayout_8.addWidget(self.rdoutElbowJC, 0, QtCore.Qt.AlignLeft)
        self.rdoutWristJC = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.rdoutWristJC.setFont(font)
        self.rdoutWristJC.setObjectName(_fromUtf8("rdoutWristJC"))
        self.verticalLayout_8.addWidget(self.rdoutWristJC, 0, QtCore.Qt.AlignLeft)
        self.layoutWidget_3 = QtGui.QWidget(self.OutputFrame)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 40, 66, 234))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.BLabel = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.BLabel.setFont(font)
        self.BLabel.setObjectName(_fromUtf8("BLabel"))
        self.verticalLayout_9.addWidget(self.BLabel, 0, QtCore.Qt.AlignRight)
        self.SLabel = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.SLabel.setFont(font)
        self.SLabel.setObjectName(_fromUtf8("SLabel"))
        self.verticalLayout_9.addWidget(self.SLabel, 0, QtCore.Qt.AlignRight)
        self.ELabel = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.ELabel.setFont(font)
        self.ELabel.setObjectName(_fromUtf8("ELabel"))
        self.verticalLayout_9.addWidget(self.ELabel, 0, QtCore.Qt.AlignRight)
        self.WLabel = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.WLabel.setFont(font)
        self.WLabel.setObjectName(_fromUtf8("WLabel"))
        self.verticalLayout_9.addWidget(self.WLabel, 0, QtCore.Qt.AlignRight)
        self.layoutWidget_4 = QtGui.QWidget(self.OutputFrame)
        self.layoutWidget_4.setGeometry(QtCore.QRect(170, 340, 131, 234))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.rdoutX = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.rdoutX.setFont(font)
        self.rdoutX.setObjectName(_fromUtf8("rdoutX"))
        self.verticalLayout_12.addWidget(self.rdoutX, 0, QtCore.Qt.AlignLeft)
        self.rdoutY = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.rdoutY.setFont(font)
        self.rdoutY.setObjectName(_fromUtf8("rdoutY"))
        self.verticalLayout_12.addWidget(self.rdoutY, 0, QtCore.Qt.AlignLeft)
        self.rdoutZ = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.rdoutZ.setFont(font)
        self.rdoutZ.setObjectName(_fromUtf8("rdoutZ"))
        self.verticalLayout_12.addWidget(self.rdoutZ, 0, QtCore.Qt.AlignLeft)
        self.rdoutT = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.rdoutT.setFont(font)
        self.rdoutT.setObjectName(_fromUtf8("rdoutT"))
        self.verticalLayout_12.addWidget(self.rdoutT, 0, QtCore.Qt.AlignLeft)
        self.layoutWidget_5 = QtGui.QWidget(self.OutputFrame)
        self.layoutWidget_5.setGeometry(QtCore.QRect(0, 340, 98, 234))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.XLabel = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.XLabel.setFont(font)
        self.XLabel.setObjectName(_fromUtf8("XLabel"))
        self.verticalLayout_13.addWidget(self.XLabel, 0, QtCore.Qt.AlignRight)
        self.YLabel = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.YLabel.setFont(font)
        self.YLabel.setObjectName(_fromUtf8("YLabel"))
        self.verticalLayout_13.addWidget(self.YLabel, 0, QtCore.Qt.AlignRight)
        self.ZLabel = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.ZLabel.setFont(font)
        self.ZLabel.setObjectName(_fromUtf8("ZLabel"))
        self.verticalLayout_13.addWidget(self.ZLabel, 0, QtCore.Qt.AlignRight)
        self.TLabel = QtGui.QLabel(self.layoutWidget_5)
        self.TLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(18)
        self.TLabel.setFont(font)
        self.TLabel.setObjectName(_fromUtf8("TLabel"))
        self.verticalLayout_13.addWidget(self.TLabel, 0, QtCore.Qt.AlignRight)
        self.btn_estop = QtGui.QPushButton(self.centralwidget)
        self.btn_estop.setGeometry(QtCore.QRect(1860, 160, 311, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_estop.setFont(font)
        self.btn_estop.setObjectName(_fromUtf8("btn_estop"))
        self.btn_exec = QtGui.QPushButton(self.centralwidget)
        self.btn_exec.setGeometry(QtCore.QRect(1860, 240, 311, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exec.setFont(font)
        self.btn_exec.setObjectName(_fromUtf8("btn_exec"))
        self.radioVideo = QtGui.QRadioButton(self.centralwidget)
        self.radioVideo.setGeometry(QtCore.QRect(510, 20, 120, 25))
        self.radioVideo.setChecked(True)
        self.radioVideo.setAutoExclusive(True)
        self.radioVideo.setObjectName(_fromUtf8("radioVideo"))
        self.radioUsr2 = QtGui.QRadioButton(self.centralwidget)
        self.radioUsr2.setGeometry(QtCore.QRect(960, 20, 120, 25))
        self.radioUsr2.setObjectName(_fromUtf8("radioUsr2"))
        self.radioDepth = QtGui.QRadioButton(self.centralwidget)
        self.radioDepth.setGeometry(QtCore.QRect(660, 20, 120, 25))
        self.radioDepth.setObjectName(_fromUtf8("radioDepth"))
        self.radioUsr1 = QtGui.QRadioButton(self.centralwidget)
        self.radioUsr1.setGeometry(QtCore.QRect(810, 20, 120, 25))
        self.radioUsr1.setObjectName(_fromUtf8("radioUsr1"))
        self.SliderFrame = QtGui.QGroupBox(self.centralwidget)
        self.SliderFrame.setGeometry(QtCore.QRect(640, 1000, 1031, 361))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.SliderFrame.setFont(font)
        self.SliderFrame.setObjectName(_fromUtf8("SliderFrame"))
        self.layoutWidget_6 = QtGui.QWidget(self.SliderFrame)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 40, 491, 251))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.sldrBase = QtGui.QSlider(self.layoutWidget_6)
        self.sldrBase.setMinimum(-179)
        self.sldrBase.setMaximum(180)
        self.sldrBase.setOrientation(QtCore.Qt.Horizontal)
        self.sldrBase.setObjectName(_fromUtf8("sldrBase"))
        self.verticalLayout_2.addWidget(self.sldrBase)
        self.sldrShoulder = QtGui.QSlider(self.layoutWidget_6)
        self.sldrShoulder.setMinimum(-179)
        self.sldrShoulder.setMaximum(180)
        self.sldrShoulder.setOrientation(QtCore.Qt.Horizontal)
        self.sldrShoulder.setObjectName(_fromUtf8("sldrShoulder"))
        self.verticalLayout_2.addWidget(self.sldrShoulder)
        self.sldrElbow = QtGui.QSlider(self.layoutWidget_6)
        self.sldrElbow.setMinimum(-179)
        self.sldrElbow.setMaximum(180)
        self.sldrElbow.setOrientation(QtCore.Qt.Horizontal)
        self.sldrElbow.setObjectName(_fromUtf8("sldrElbow"))
        self.verticalLayout_2.addWidget(self.sldrElbow)
        self.sldrWrist = QtGui.QSlider(self.layoutWidget_6)
        self.sldrWrist.setMinimum(-179)
        self.sldrWrist.setMaximum(180)
        self.sldrWrist.setOrientation(QtCore.Qt.Horizontal)
        self.sldrWrist.setObjectName(_fromUtf8("sldrWrist"))
        self.verticalLayout_2.addWidget(self.sldrWrist)
        self.layoutWidget_7 = QtGui.QWidget(self.SliderFrame)
        self.layoutWidget_7.setGeometry(QtCore.QRect(510, 40, 61, 251))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.rdoutBase = QtGui.QLabel(self.layoutWidget_7)
        self.rdoutBase.setObjectName(_fromUtf8("rdoutBase"))
        self.verticalLayout_6.addWidget(self.rdoutBase)
        self.rdoutShoulder = QtGui.QLabel(self.layoutWidget_7)
        self.rdoutShoulder.setObjectName(_fromUtf8("rdoutShoulder"))
        self.verticalLayout_6.addWidget(self.rdoutShoulder)
        self.rdoutElbow = QtGui.QLabel(self.layoutWidget_7)
        self.rdoutElbow.setObjectName(_fromUtf8("rdoutElbow"))
        self.verticalLayout_6.addWidget(self.rdoutElbow)
        self.rdoutWrist = QtGui.QLabel(self.layoutWidget_7)
        self.rdoutWrist.setObjectName(_fromUtf8("rdoutWrist"))
        self.verticalLayout_6.addWidget(self.rdoutWrist)
        self.sldrGrip1 = QtGui.QSlider(self.SliderFrame)
        self.sldrGrip1.setGeometry(QtCore.QRect(10, 310, 260, 29))
        self.sldrGrip1.setMinimum(-179)
        self.sldrGrip1.setMaximum(180)
        self.sldrGrip1.setOrientation(QtCore.Qt.Horizontal)
        self.sldrGrip1.setObjectName(_fromUtf8("sldrGrip1"))
        self.sldrGrip2 = QtGui.QSlider(self.SliderFrame)
        self.sldrGrip2.setGeometry(QtCore.QRect(360, 310, 261, 29))
        self.sldrGrip2.setMinimum(-179)
        self.sldrGrip2.setMaximum(180)
        self.sldrGrip2.setOrientation(QtCore.Qt.Horizontal)
        self.sldrGrip2.setObjectName(_fromUtf8("sldrGrip2"))
        self.rdoutGrip1 = QtGui.QLabel(self.SliderFrame)
        self.rdoutGrip1.setGeometry(QtCore.QRect(290, 310, 49, 28))
        self.rdoutGrip1.setObjectName(_fromUtf8("rdoutGrip1"))
        self.rdoutGrip2 = QtGui.QLabel(self.SliderFrame)
        self.rdoutGrip2.setGeometry(QtCore.QRect(640, 310, 49, 28))
        self.rdoutGrip2.setObjectName(_fromUtf8("rdoutGrip2"))
        self.sldrMaxTorque = QtGui.QSlider(self.SliderFrame)
        self.sldrMaxTorque.setEnabled(True)
        self.sldrMaxTorque.setGeometry(QtCore.QRect(635, 40, 31, 181))
        self.sldrMaxTorque.setMaximum(100)
        self.sldrMaxTorque.setProperty("value", 50)
        self.sldrMaxTorque.setOrientation(QtCore.Qt.Vertical)
        self.sldrMaxTorque.setObjectName(_fromUtf8("sldrMaxTorque"))
        self.rdoutTorq = QtGui.QLabel(self.SliderFrame)
        self.rdoutTorq.setGeometry(QtCore.QRect(640, 230, 50, 28))
        self.rdoutTorq.setObjectName(_fromUtf8("rdoutTorq"))
        self.sldrSpeed = QtGui.QSlider(self.SliderFrame)
        self.sldrSpeed.setEnabled(True)
        self.sldrSpeed.setGeometry(QtCore.QRect(755, 40, 31, 181))
        self.sldrSpeed.setMaximum(100)
        self.sldrSpeed.setProperty("value", 25)
        self.sldrSpeed.setSliderPosition(25)
        self.sldrSpeed.setOrientation(QtCore.Qt.Vertical)
        self.sldrSpeed.setObjectName(_fromUtf8("sldrSpeed"))
        self.TqLabel = QtGui.QLabel(self.SliderFrame)
        self.TqLabel.setGeometry(QtCore.QRect(606, 10, 101, 20))
        self.TqLabel.setObjectName(_fromUtf8("TqLabel"))
        self.rdoutSpeed = QtGui.QLabel(self.SliderFrame)
        self.rdoutSpeed.setGeometry(QtCore.QRect(760, 230, 49, 28))
        self.rdoutSpeed.setObjectName(_fromUtf8("rdoutSpeed"))
        self.SpLabel = QtGui.QLabel(self.SliderFrame)
        self.SpLabel.setGeometry(QtCore.QRect(725, 10, 101, 21))
        self.SpLabel.setObjectName(_fromUtf8("SpLabel"))
        self.rdoutMousePixels = QtGui.QLabel(self.centralwidget)
        self.rdoutMousePixels.setGeometry(QtCore.QRect(520, 860, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rdoutMousePixels.setFont(font)
        self.rdoutMousePixels.setTextFormat(QtCore.Qt.AutoText)
        self.rdoutMousePixels.setObjectName(_fromUtf8("rdoutMousePixels"))
        self.rdoutMouseWorld = QtGui.QLabel(self.centralwidget)
        self.rdoutMouseWorld.setGeometry(QtCore.QRect(1170, 860, 151, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rdoutMouseWorld.setFont(font)
        self.rdoutMouseWorld.setTextFormat(QtCore.Qt.AutoText)
        self.rdoutMouseWorld.setObjectName(_fromUtf8("rdoutMouseWorld"))
        self.PixelCoordLabel_2 = QtGui.QLabel(self.centralwidget)
        self.PixelCoordLabel_2.setGeometry(QtCore.QRect(1170, 820, 371, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PixelCoordLabel_2.setFont(font)
        self.PixelCoordLabel_2.setObjectName(_fromUtf8("PixelCoordLabel_2"))
        self.PixelCoordLabel = QtGui.QLabel(self.centralwidget)
        self.PixelCoordLabel.setGeometry(QtCore.QRect(510, 820, 291, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PixelCoordLabel.setFont(font)
        self.PixelCoordLabel.setObjectName(_fromUtf8("PixelCoordLabel"))
        self.btn_task1 = QtGui.QPushButton(self.centralwidget)
        self.btn_task1.setGeometry(QtCore.QRect(1860, 320, 311, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_task1.setFont(font)
        self.btn_task1.setObjectName(_fromUtf8("btn_task1"))
        self.btn_task2 = QtGui.QPushButton(self.centralwidget)
        self.btn_task2.setGeometry(QtCore.QRect(1860, 400, 311, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_task2.setFont(font)
        self.btn_task2.setObjectName(_fromUtf8("btn_task2"))
        self.btn_task3 = QtGui.QPushButton(self.centralwidget)
        self.btn_task3.setGeometry(QtCore.QRect(1860, 480, 311, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_task3.setFont(font)
        self.btn_task3.setObjectName(_fromUtf8("btn_task3"))
        self.btn_task4 = QtGui.QPushButton(self.centralwidget)
        self.btn_task4.setGeometry(QtCore.QRect(1860, 560, 311, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_task4.setFont(font)
        self.btn_task4.setObjectName(_fromUtf8("btn_task4"))
        self.btn_exec_6 = QtGui.QPushButton(self.centralwidget)
        self.btn_exec_6.setGeometry(QtCore.QRect(1860, 640, 311, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exec_6.setFont(font)
        self.btn_exec_6.setObjectName(_fromUtf8("btn_exec_6"))
        self.layoutWidget_8 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_8.setGeometry(QtCore.QRect(110, 670, 221, 728))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.Group2 = QtGui.QVBoxLayout(self.layoutWidget_8)
        self.Group2.setMargin(10)
        self.Group2.setObjectName(_fromUtf8("Group2"))
        self.btnUser1 = QtGui.QPushButton(self.layoutWidget_8)
        self.btnUser1.setObjectName(_fromUtf8("btnUser1"))
        self.Group2.addWidget(self.btnUser1)
        self.btnUser2 = QtGui.QPushButton(self.layoutWidget_8)
        self.btnUser2.setObjectName(_fromUtf8("btnUser2"))
        self.Group2.addWidget(self.btnUser2)
        self.btnUser3 = QtGui.QPushButton(self.layoutWidget_8)
        self.btnUser3.setObjectName(_fromUtf8("btnUser3"))
        self.Group2.addWidget(self.btnUser3)
        self.btnUser4 = QtGui.QPushButton(self.layoutWidget_8)
        self.btnUser4.setObjectName(_fromUtf8("btnUser4"))
        self.Group2.addWidget(self.btnUser4)
        self.btnUser5 = QtGui.QPushButton(self.layoutWidget_8)
        self.btnUser5.setObjectName(_fromUtf8("btnUser5"))
        self.Group2.addWidget(self.btnUser5)
        self.btnUser6 = QtGui.QPushButton(self.layoutWidget_8)
        self.btnUser6.setObjectName(_fromUtf8("btnUser6"))
        self.Group2.addWidget(self.btnUser6)
        self.btnUser7 = QtGui.QPushButton(self.layoutWidget_8)
        self.btnUser7.setObjectName(_fromUtf8("btnUser7"))
        self.Group2.addWidget(self.btnUser7)
        self.btnUser8 = QtGui.QPushButton(self.layoutWidget_8)
        self.btnUser8.setObjectName(_fromUtf8("btnUser8"))
        self.Group2.addWidget(self.btnUser8)
        self.btnUser9 = QtGui.QPushButton(self.layoutWidget_8)
        self.btnUser9.setObjectName(_fromUtf8("btnUser9"))
        self.Group2.addWidget(self.btnUser9)
        self.btnUser10 = QtGui.QPushButton(self.layoutWidget_8)
        self.btnUser10.setAutoRepeatDelay(300)
        self.btnUser10.setObjectName(_fromUtf8("btnUser10"))
        self.Group2.addWidget(self.btnUser10)
        self.btnUser11 = QtGui.QPushButton(self.layoutWidget_8)
        self.btnUser11.setAutoRepeatDelay(300)
        self.btnUser11.setObjectName(_fromUtf8("btnUser11"))
        self.Group2.addWidget(self.btnUser11)
        self.btnUser12 = QtGui.QPushButton(self.layoutWidget_8)
        self.btnUser12.setAutoRepeatDelay(300)
        self.btnUser12.setObjectName(_fromUtf8("btnUser12"))
        self.Group2.addWidget(self.btnUser12)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 1440, 1211, 51))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.rdoutStatus = QtGui.QLabel(self.groupBox)
        self.rdoutStatus.setGeometry(QtCore.QRect(130, 0, 905, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rdoutStatus.setFont(font)
        self.rdoutStatus.setTextFormat(QtCore.Qt.AutoText)
        self.rdoutStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.rdoutStatus.setObjectName(_fromUtf8("rdoutStatus"))
        self.GzFrame = QtGui.QFrame(self.centralwidget)
        self.GzFrame.setGeometry(QtCore.QRect(1770, 780, 441, 621))
        self.GzFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.GzFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.GzFrame.setObjectName(_fromUtf8("GzFrame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.GzFrame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.WorldCoordLabel_2 = QtGui.QLabel(self.GzFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.WorldCoordLabel_2.setFont(font)
        self.WorldCoordLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.WorldCoordLabel_2.setObjectName(_fromUtf8("WorldCoordLabel_2"))
        self.verticalLayout_3.addWidget(self.WorldCoordLabel_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.GzBLabel = QtGui.QLabel(self.GzFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(14)
        self.GzBLabel.setFont(font)
        self.GzBLabel.setObjectName(_fromUtf8("GzBLabel"))
        self.horizontalLayout_3.addWidget(self.GzBLabel)
        self.GzrdoutBaseJC = QtGui.QLabel(self.GzFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(14)
        self.GzrdoutBaseJC.setFont(font)
        self.GzrdoutBaseJC.setObjectName(_fromUtf8("GzrdoutBaseJC"))
        self.horizontalLayout_3.addWidget(self.GzrdoutBaseJC)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.GzSLabel = QtGui.QLabel(self.GzFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(14)
        self.GzSLabel.setFont(font)
        self.GzSLabel.setObjectName(_fromUtf8("GzSLabel"))
        self.horizontalLayout_4.addWidget(self.GzSLabel)
        self.GzrdoutShoulderJC = QtGui.QLabel(self.GzFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(14)
        self.GzrdoutShoulderJC.setFont(font)
        self.GzrdoutShoulderJC.setObjectName(_fromUtf8("GzrdoutShoulderJC"))
        self.horizontalLayout_4.addWidget(self.GzrdoutShoulderJC)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.GzELabel = QtGui.QLabel(self.GzFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(14)
        self.GzELabel.setFont(font)
        self.GzELabel.setObjectName(_fromUtf8("GzELabel"))
        self.horizontalLayout_5.addWidget(self.GzELabel)
        self.GzrdoutElbowJC = QtGui.QLabel(self.GzFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(14)
        self.GzrdoutElbowJC.setFont(font)
        self.GzrdoutElbowJC.setObjectName(_fromUtf8("GzrdoutElbowJC"))
        self.horizontalLayout_5.addWidget(self.GzrdoutElbowJC)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.GzWLabel = QtGui.QLabel(self.GzFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(14)
        self.GzWLabel.setFont(font)
        self.GzWLabel.setObjectName(_fromUtf8("GzWLabel"))
        self.horizontalLayout_6.addWidget(self.GzWLabel)
        self.GzrdoutWristJC = QtGui.QLabel(self.GzFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(14)
        self.GzrdoutWristJC.setFont(font)
        self.GzrdoutWristJC.setObjectName(_fromUtf8("GzrdoutWristJC"))
        self.horizontalLayout_6.addWidget(self.GzrdoutWristJC)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.GzEELabelX = QtGui.QLabel(self.GzFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(14)
        self.GzEELabelX.setFont(font)
        self.GzEELabelX.setObjectName(_fromUtf8("GzEELabelX"))
        self.horizontalLayout_9.addWidget(self.GzEELabelX)
        self.GzEEX = QtGui.QLabel(self.GzFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(14)
        self.GzEEX.setFont(font)
        self.GzEEX.setObjectName(_fromUtf8("GzEEX"))
        self.horizontalLayout_9.addWidget(self.GzEEX)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.GzEELabelY = QtGui.QLabel(self.GzFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(14)
        self.GzEELabelY.setFont(font)
        self.GzEELabelY.setObjectName(_fromUtf8("GzEELabelY"))
        self.horizontalLayout_10.addWidget(self.GzEELabelY)
        self.GzEEY = QtGui.QLabel(self.GzFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(14)
        self.GzEEY.setFont(font)
        self.GzEEY.setObjectName(_fromUtf8("GzEEY"))
        self.horizontalLayout_10.addWidget(self.GzEEY)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.GzEELabelZ = QtGui.QLabel(self.GzFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(14)
        self.GzEELabelZ.setFont(font)
        self.GzEELabelZ.setObjectName(_fromUtf8("GzEELabelZ"))
        self.horizontalLayout_11.addWidget(self.GzEELabelZ)
        self.GzEEZ = QtGui.QLabel(self.GzFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(14)
        self.GzEEZ.setFont(font)
        self.GzEEZ.setObjectName(_fromUtf8("GzEEZ"))
        self.horizontalLayout_11.addWidget(self.GzEEZ)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnClearTrj = QtGui.QPushButton(self.GzFrame)
        self.btnClearTrj.setObjectName(_fromUtf8("btnClearTrj"))
        self.horizontalLayout.addWidget(self.btnClearTrj)
        self.chk_showtrj = QtGui.QCheckBox(self.GzFrame)
        self.chk_showtrj.setObjectName(_fromUtf8("chk_showtrj"))
        self.horizontalLayout.addWidget(self.chk_showtrj)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.btnAddCube = QtGui.QPushButton(self.GzFrame)
        self.btnAddCube.setObjectName(_fromUtf8("btnAddCube"))
        self.verticalLayout_3.addWidget(self.btnAddCube)
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(500, 930, 577, 42))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.chk_simulation = QtGui.QCheckBox(self.layoutWidget)
        self.chk_simulation.setChecked(True)
        self.chk_simulation.setObjectName(_fromUtf8("chk_simulation"))
        self.horizontalLayout_2.addWidget(self.chk_simulation)
        self.chk_attached = QtGui.QCheckBox(self.layoutWidget)
        self.chk_attached.setChecked(False)
        self.chk_attached.setObjectName(_fromUtf8("chk_attached"))
        self.horizontalLayout_2.addWidget(self.chk_attached)
        self.chk_directcontrol = QtGui.QCheckBox(self.layoutWidget)
        self.chk_directcontrol.setChecked(False)
        self.chk_directcontrol.setObjectName(_fromUtf8("chk_directcontrol"))
        self.horizontalLayout_2.addWidget(self.chk_directcontrol)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(500, 1040, 131, 241))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.BLabelS = QtGui.QLabel(self.layoutWidget1)
        self.BLabelS.setObjectName(_fromUtf8("BLabelS"))
        self.verticalLayout.addWidget(self.BLabelS, 0, QtCore.Qt.AlignRight)
        self.SLabelS = QtGui.QLabel(self.layoutWidget1)
        self.SLabelS.setObjectName(_fromUtf8("SLabelS"))
        self.verticalLayout.addWidget(self.SLabelS, 0, QtCore.Qt.AlignRight)
        self.ELabelS = QtGui.QLabel(self.layoutWidget1)
        self.ELabelS.setObjectName(_fromUtf8("ELabelS"))
        self.verticalLayout.addWidget(self.ELabelS, 0, QtCore.Qt.AlignRight)
        self.WLabelS = QtGui.QLabel(self.layoutWidget1)
        self.WLabelS.setObjectName(_fromUtf8("WLabelS"))
        self.verticalLayout.addWidget(self.WLabelS, 0, QtCore.Qt.AlignRight)
        self.G1LableS = QtGui.QLabel(self.centralwidget)
        self.G1LableS.setGeometry(QtCore.QRect(550, 1300, 81, 51))
        self.G1LableS.setObjectName(_fromUtf8("G1LableS"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.videoDisplay.setText(_translate("MainWindow", "Video Display", None))
        self.JointCoordLabel.setText(_translate("MainWindow", "Joint Coordinates", None))
        self.WorldCoordLabel.setText(_translate("MainWindow", "End Effector Location", None))
        self.rdoutBaseJC.setText(_translate("MainWindow", "0", None))
        self.rdoutShoulderJC.setText(_translate("MainWindow", "0", None))
        self.rdoutElbowJC.setText(_translate("MainWindow", "0", None))
        self.rdoutWristJC.setText(_translate("MainWindow", "0", None))
        self.BLabel.setText(_translate("MainWindow", "B:", None))
        self.SLabel.setText(_translate("MainWindow", "S:", None))
        self.ELabel.setText(_translate("MainWindow", "E:", None))
        self.WLabel.setText(_translate("MainWindow", "W:", None))
        self.rdoutX.setText(_translate("MainWindow", "0", None))
        self.rdoutY.setText(_translate("MainWindow", "0", None))
        self.rdoutZ.setText(_translate("MainWindow", "0", None))
        self.rdoutT.setText(_translate("MainWindow", "0", None))
        self.XLabel.setText(_translate("MainWindow", "X:", None))
        self.YLabel.setText(_translate("MainWindow", "Y:", None))
        self.ZLabel.setText(_translate("MainWindow", "Z:", None))
        self.TLabel.setText(_translate("MainWindow", "Phi:", None))
        self.btn_estop.setText(_translate("MainWindow", "EMERGENCY STOP", None))
        self.btn_exec.setText(_translate("MainWindow", "EXECUTE PLAN", None))
        self.radioVideo.setText(_translate("MainWindow", "Video", None))
        self.radioUsr2.setText(_translate("MainWindow", "User 2", None))
        self.radioDepth.setText(_translate("MainWindow", "Depth", None))
        self.radioUsr1.setText(_translate("MainWindow", "User 1", None))
        self.SliderFrame.setTitle(_translate("MainWindow", "Joint Sliders", None))
        self.rdoutBase.setText(_translate("MainWindow", "0", None))
        self.rdoutShoulder.setText(_translate("MainWindow", "0", None))
        self.rdoutElbow.setText(_translate("MainWindow", "0", None))
        self.rdoutWrist.setText(_translate("MainWindow", "0", None))
        self.rdoutGrip1.setText(_translate("MainWindow", "0", None))
        self.rdoutGrip2.setText(_translate("MainWindow", "0", None))
        self.rdoutTorq.setText(_translate("MainWindow", "0", None))
        self.TqLabel.setText(_translate("MainWindow", "Torque", None))
        self.rdoutSpeed.setText(_translate("MainWindow", "0", None))
        self.SpLabel.setText(_translate("MainWindow", "Speed", None))
        self.rdoutMousePixels.setText(_translate("MainWindow", "(U,V,D)", None))
        self.rdoutMouseWorld.setText(_translate("MainWindow", "(X,Y,Z)", None))
        self.PixelCoordLabel_2.setText(_translate("MainWindow", "World Coordinates [mm]:", None))
        self.PixelCoordLabel.setText(_translate("MainWindow", "Mouse Coordinates:", None))
        self.btn_task1.setText(_translate("MainWindow", "TASK 1", None))
        self.btn_task2.setText(_translate("MainWindow", "TASK 2", None))
        self.btn_task3.setText(_translate("MainWindow", "TASK 3", None))
        self.btn_task4.setText(_translate("MainWindow", "TASK 4", None))
        self.btn_exec_6.setText(_translate("MainWindow", "TASK 5", None))
        self.btnUser1.setText(_translate("MainWindow", "USER 1", None))
        self.btnUser2.setText(_translate("MainWindow", "USER 2", None))
        self.btnUser3.setText(_translate("MainWindow", "USER 3", None))
        self.btnUser4.setText(_translate("MainWindow", "USER 4", None))
        self.btnUser5.setText(_translate("MainWindow", "USER 5", None))
        self.btnUser6.setText(_translate("MainWindow", "USER 6", None))
        self.btnUser7.setText(_translate("MainWindow", "USER 7", None))
        self.btnUser8.setText(_translate("MainWindow", "USER 8", None))
        self.btnUser9.setText(_translate("MainWindow", "USER 9", None))
        self.btnUser10.setText(_translate("MainWindow", "USER 10", None))
        self.btnUser11.setText(_translate("MainWindow", "USER 11", None))
        self.btnUser12.setText(_translate("MainWindow", "USER 12", None))
        self.groupBox.setTitle(_translate("MainWindow", "STATUS: ", None))
        self.rdoutStatus.setText(_translate("MainWindow", "Waiting for Inputs", None))
        self.WorldCoordLabel_2.setText(_translate("MainWindow", "Gazebo Messages", None))
        self.GzBLabel.setText(_translate("MainWindow", "B:", None))
        self.GzrdoutBaseJC.setText(_translate("MainWindow", "0", None))
        self.GzSLabel.setText(_translate("MainWindow", "S:", None))
        self.GzrdoutShoulderJC.setText(_translate("MainWindow", "0", None))
        self.GzELabel.setText(_translate("MainWindow", "E:", None))
        self.GzrdoutElbowJC.setText(_translate("MainWindow", "0", None))
        self.GzWLabel.setText(_translate("MainWindow", "W:", None))
        self.GzrdoutWristJC.setText(_translate("MainWindow", "0", None))
        self.GzEELabelX.setText(_translate("MainWindow", "X:", None))
        self.GzEEX.setText(_translate("MainWindow", "0", None))
        self.GzEELabelY.setText(_translate("MainWindow", "Y:", None))
        self.GzEEY.setText(_translate("MainWindow", "0", None))
        self.GzEELabelZ.setText(_translate("MainWindow", "Z:", None))
        self.GzEEZ.setText(_translate("MainWindow", "0", None))
        self.btnClearTrj.setText(_translate("MainWindow", "Clear", None))
        self.chk_showtrj.setText(_translate("MainWindow", "Show", None))
        self.btnAddCube.setText(_translate("MainWindow", "+Add Cube", None))
        self.chk_simulation.setText(_translate("MainWindow", "Simulation", None))
        self.chk_attached.setText(_translate("MainWindow", "Attach", None))
        self.chk_directcontrol.setText(_translate("MainWindow", "Direct Control", None))
        self.BLabelS.setText(_translate("MainWindow", "Base", None))
        self.SLabelS.setText(_translate("MainWindow", "Shoulder", None))
        self.ELabelS.setText(_translate("MainWindow", "Elbow", None))
        self.WLabelS.setText(_translate("MainWindow", "Wrist", None))
        self.G1LableS.setText(_translate("MainWindow", "Grip 1", None))

